# Generated by Django 3.0.5 on 2020-05-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='stripe_id',
            new_name='stripe_card_id',
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_card_id', models.CharField(max_length=120)),
                ('paid', models.BooleanField(default=True)),
                ('refunded', models.BooleanField(default=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=120, null=True)),
                ('seller_message', models.CharField(blank=True, max_length=120, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=120, null=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billing.BillingProfile')),
            ],
        ),
    ]
