"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cbq4&+1fyhc%33xe3dq1y1k2g)8!mx5!*l*7e-j=vo3^9__)tm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",
    "products",
    "search",
    "tags",
    "cart",
    "orders",
    "accounts",
    "billing",
    "address",
    "analytics",
]

SITE_ID=1

AUTH_USER_MODEL='accounts.User'
LOGIN_URL='/account/login/'
LOGIN_REDIRECT_URL='/'
LOGOUT_URL='/account/logout/'
LOGOUT_REDIRECT_URL='/account/login/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,"static-storage")
]

STATIC_ROOT=os.path.join(os.path.dirname(BASE_DIR),"static-cdn","static_root")



MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(os.path.dirname(BASE_DIR),"static_cdn","media_root")


PROTECTED_ROOT=os.path.join(os.path.dirname(BASE_DIR),'static_cdn','protected_media')





STRIPE_SECRET_KEY='sk_test_HwvAUIsohGImpP7zwFEZvO6q00xd5DlMjJ'
STRIPE_PUB_KEY='pk_test_Q9ekfzPOPmbrzSluWQO8e5CT00nBpE2Xkk'


""" EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='nurhasnatseam2@gmail.com'
EMAIL_HOST_PASSWORD='nazrulislam'
EMAIL_PORT=587
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL='PYHON ECOMMERCE FROM YOUR SERVER' """


#email settings for local use all the email would be sent to local file
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = 'tmp/email-messages/'




CORS_REPLACE_HTTPS_REFERER    = True 
HOST_SCHEME                   = 'https://'
SECURE_PROXY_SSL_HEADER       = ('HTTP_X_FORWARDED_PROTO','https')
SECURE_SSL_REDIRECT           = True 
SESSION_COOKIE_SECURE         = True 
CSRF_COOKIE_SECURE            = True 
SECURE_HSTS_INCLUDE_SUBDOMAINS      = True 
SECURE_HSTS_SECONDS           = 1000000
SECURE_FRAME_DENY             = True