# Generated by Django 3.0.5 on 2020-05-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200506_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='order',
            new_name='order_id',
        ),
    ]
